# Generated by Django 6.1 on 2026-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
